import Head from "next/head";

export default function NotFound() {
  return (
    <>
      <Head>
        <title>404 error!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="fixed h-full flex bottom-0 top-0 left-0 right-0 items-center ">
        <h1 className="text-3xl sm:text-5xl m-auto p-8 font-bold md:text-6xl 2xl:text-9xl">NOT FOUNDED!</h1>
      </div>
    </>
  );
}
