import Head from "next/head";
import Image from "next/image";
import Layout from "components/layout";
export default function Home() {
  return (
    <Layout>
      <Head>
        <title>holim log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <h1 className="text-2xl font-bold text-center my-20">Hello, Welcome to my Blog!</h1>
    </Layout>
  );
}
